### ISSUE TITLE
Error when using "apply all changes"

### ISSUE THREAD

**Issue by poulet67** [Rimpotche/3D-Ear-generator#1]
Hi,

I am quite interested in using this program however I can't seem to get the apply all changes button to work. I get the following error:

Python: Traceback (most recent call last):
  File "C:\3D-Ear-generator-master (1)\3D-Ear-generator-master\api_new_ear_en\api_new_ear_en.blend\new_ear.py", line 1227, in execute
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

**Comment by Rimpotche** [comment]
Salut, Poulet67.
I received today 2021-12-21 your notification. I read that you sent it on Oct 1. Sorry for the delay but not my fault. I made this script (my very only script) long ago without real python knowledge. So I really cannot solve your problem. Which version of Blender ? That may be the cause, because it worked if you followed all my advices. I made it under 2.80. I could not update it. Thanks for trying my API.

**Comment by poulet67** [comment]
Bonjour de Canada,

I am a bit new to GitHub and was trying to remove my issue. Didn’t mean to send you a bunch of notifications

Truth be told I have fixed it already. I tried a few different versions of blender and none of them worked.

The issue is around line 1227 of the script:

        bpy.ops.object.modifier_apply(apply_as='SHAPE', modifier="Armature")

I think this API call has been depreciated. I had to change it to this to get it to work:

       bpy.ops.object.modifier_apply_as_shapekey(modifier="Armature")

I’ll leave it to you if you’d like to update it or not.

Cheers

**Comment by Sitwayen** [comment]
@poulet67 This works for me as well, thank you
